language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=tests.settings
  - export PYTHONPATH=${PYTHONPATH}:tests/
install:
  - pip install .
  - pip install -r requirements/test.txt Django==$DJANGO
before_script:
  - flake8 consent --exclude=migrations
script:
  - make test
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
notifications:
  irc:
    channels:
      - "irc.freenode.org#pacha"